name:                "discordant"
version:             "0.1.0.0"
github:              "githubuser/discordant"
license:             "BSD3"
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# synopsis:            Short description of your package
# category:            Web

description:         "README at <https://github.com/githubuser/discordant#readme>"

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- generic-lens
- lens
- protolude
- text
- uuid
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  discordant:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discordant

tests:
  discordant-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discordant
    - QuickCheck
    - hspec
    - tasty
    - tasty-discover
    - tasty-hspec
    - tasty-quickcheck
