name:                "discordant"
version:             "0.1.0.0"
github:              "lgastako/discordant"
license:             "BSD3"
author:              "John Evans"
maintainer:          "lgastako@gmail.com"
copyright:           "2024 John Evans"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            "Reformat Discord logs"
category:            "Web"

description:         "README at <https://github.com/lgastako/discordant#readme>"

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- generic-lens
- lens
- protolude
- random
- text
- uuid
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  discordant:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - attoparsec

